.TH AVA-CLI "1" "June 2016" "ava-cli 0.12"
.SH NAME
ava-cli \- a remote procedure call client for Ava Core. 
.SH SYNOPSIS
ava-cli [options] <command> [params] \- Send command to Ava Core. 
.TP
ava-cli [options] help \- Asks Ava Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the ava-cli program. ava-cli is an RPC client used to send commands to Ava Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBavad\fP, \fBava.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
